[build]
  command = "npm run build"
  publish = "./dist"

[dev]
  command = ""
  publish = "./dist"


# Do this instead of looking for a shortlink redirect 
# so we can serve local images 
[[redirects]]
  from = "/image/*"
  to = "/image/:splat"
  status = 200


# Tu invitación en la raíz
[[redirects]]
  from = "/"
  to = "https://camiloyalejandra12diciembre.my.canva.site/"
  status = 301

# Redirigir cualquier otro error a la invitación también
[[redirects]]
  from = "/*"
  to = "https://camiloyalejandra12diciembre.my.canva.site/"
  status = 302
